language: python

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
        - python: pypy2.7-5.8.0
          env: TOXENV=pypy
        - python: pypy3.5-5.8.0
          env: TOXENV=pypy3

install:
  - pip install tox

script: tox
